leaflet sorter now only runs on lipids within rmax
BranniganLab/density_threshold_affinity pull request #102
Opened 2024-12-06 19:33 UTC by JesseSandberg

## Description
When running polarDensityBin the leaflet sorter would run on all lipids in the system, even those outside of the zone of analysis. This PR fixes that.

## Usage Changes
None

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] Leaflet sorting only selects lipids within Rmax

## Pre-Review checklist (PR maker)
- [ ] Run same analysis twice - once prior to change and once after change - and then vimdiff the outputs to ensure they are identical

## Review checklist (Reviewer)
- [ ] No missed "low-hanging fruit" that would substantially aid readability.
- [ ] Any "high-hanging" or "rotten" fruit is added to the issues list.
- [ ] I understand what the changes are doing and how
- [ ] I understand the motivation for this PR (the PR itself is appropriately documented)

## Status
- [ ] Ready for review

2024-12-06 20:04 UTC, JesseSandberg commented
closed because I found aberrant behavior with lipids that were only partially enclosed in the shell created by Rmax

2024-12-10 15:38 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -        trajectory_leaflet_assignment "resname $species" $headname $tailname $lipidbeads_selstr
This is just deleting extra blank spaces

2024-12-10 15:38 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -        set totals [frame_leaflet_assignment "resname $species" $headname $tailname $lipidbeads_selstr $params(start_frame) $params(start_frame)]
This switches the expected density measurement to use the end_frame instead of the start_frame

2024-12-10 15:39 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -        Ntheta 50
Deleted a bunch of extra spaces after 50

2024-12-10 15:40 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -    for {set ri $params(Rmin)} { $ri<=$params(Rmax)} { set ri [expr $ri + $params(dr)]} {
The equals sign meant that when Rmax was evenly divisible by dr, analysis would exceed Rmax by one whole shell

2024-12-10 15:41 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -        frame_leaflet_assignment $species $headname $tailname $lipidbeads_selstr $update_frame [expr $update_frame + $params(dt)]
The restrict_leaflet_sorter_to_Rmax param needs to be here (as opposed to inside the frame_leaflet_assignment proc)

2024-12-10 15:42 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -proc frame_leaflet_assignment {species headname tailname lipidbeads_selstr frame_i frame_f} {
Now has a restrict_to_Rmax arg that defaults to 0

2024-12-10 15:42 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -    set sel [ atomselect top "(($species)) and $lipidbeads_selstr"  frame $frame_i]
Now switches between cases, depending on user setting

2024-12-16 22:30 UTC, JesseSandberg commented
Note from convo today: This PR will be reviewed when I have completely replicated analysis on the nachr project from end to end with this branch and gotten the same results out as previously.

2025-01-07 20:00 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> -        set totals [[list 0 0] [list 0 0]]
This was causing an error. It is now fixed.

2025-01-07 20:16 UTC, JesseSandberg commented
As discussed in nougat meeting, I have re-run a DTA calculation from a separate project and confirmed that the site delta G does not change when these changes are made.

2025-01-10 18:24 UTC, JesseSandberg commented
As discussed in the lab, I have created a separate repo - DTA_Testing - that now houses any testing notebooks and materials created.

2025-01-23 03:18 UTC, gbrannigan commented on TCL/polarDensity_for_DTA.tcl
> +    ;# a questionable life choice.
1. It is unsafe to assume fewer than 6 decimal places. An automated pipeline often leads to excessive precision.  

2. This code is much more complicated than it needs to be. Do a simple modulo to get the remainder,  and then compare the remainder against a tolerance (not 0!). Do not make the tolerance a magic number.  

3. We do not scold others for breaking our code.  Keep the documentation judgment-free (and professional, please).

2025-01-23 03:20 UTC, gbrannigan commented on TCL/polarDensity_for_DTA.tcl
> +    }
1. This code is more complicated than it needs to be. Do a simple modulo to get the remainder,  and then compare the remainder against a tolerance (not 0!). Do not make the tolerance a magic number.  

2. It is unsafe to assume fewer than 6 decimal places. An automated pipeline often leads to excessive precision.

2025-01-23 03:27 UTC, gbrannigan requested changes
I have left two comments, please address.

2025-01-23 17:45 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
> +    ;# a questionable life choice.
Fair enough, I was not considering the automated pipeline or that someone might choose 2/3 of a nm as their dr for example. Removing.

2025-01-23 19:03 UTC, JesseSandberg commented on TCL/polarDensity_for_DTA.tcl
@gbrannigan the new proc is here

2025-01-24 21:49 UTC, merged